[features]
seeds = false
skip-lint = false
[programs.localnet]
challenge_note = "9a5SvrAssQ5QtJTkSXRZYnedFadBNjpadztEsY6wu3ug"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "/Users/jemerald/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
